# fly.toml app configuration file generated for apivrp on 2023-09-25T21:32:34-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "apivrp"
primary_region = "gdl"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
